---
- name : Descargamos la aplicación
  git:
    repo: https://github.com/Kr3n3r/proyecto_web_hosting_automatico
    dest: /tmp/app/
    clone: yes

- name : Creamos el directorio para ansible
  file :
    path: /opt/ansible
    state: directory

- name : Creamos el directorio para terraform
  file :
    path: /opt/terraform
    state: directory

- name : Creamos el par de claves ssh
  openssh_keypair :
    path : "/opt/terraform/key"
    type : rsa
    size : 4096
    state : present
    force : no

## habrá que ver quién es el usuario que va a tener permisos sobre esos archivos, porque tendrá que ser el mismo que ejecute el proceso de la aplicación.

- name: Encuentra la versión más actualizada de terraform
  uri:
    url: https://releases.hashicorp.com/terraform/index.json
    return_content: yes
  register: terraform_index
  check_mode: no

- name : Establece la versión de terraform a instalar(última)
  set_fact:
    terraform_version_to_install: "{{ (terraform_index.content | from_json).versions | reject('search','-') | list | last }}"

- name: Mira si terraform ya está instalado con la versión correspondiente
  command: "/usr/local/bin/terraform -version"
  register: terraform_installed_version
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name : Instala terraform si no está instalado ya
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version_to_install }}/terraform_{{ terraform_version_to_install }}_linux_amd64.zip"
    dest: "/usr/local/bin"
    remote_src: yes

- name : Instala AWS CLI
  shell : curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"; unzip /tmp/awscliv2.zip; ./tmp/aws/install

- name: Instalar paquetes necesarios
  apt: pkg={{ item }}
  with_items:
    - apache2
    - pip
    - git
    - unzip
    - 

- name : Instalar módulo de venv
  pip: name={{ item }}
  with_items:
    - python3-venv

- name : Crear entorno virtual de la aplicación
  pip : 
    virtualenv : /opt/app/.venv
    requirements : /tmp/app/requirements.txt

- name : Mover los archivos de la aplicación a su carpeta correspondiente
  copy : src=/tmp/app dest=/opt/app/