# Generated by Django 3.2.12 on 2022-03-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cms_type', models.CharField(choices=[(1, 'Wordpress'), (2, 'Prestashop'), (3, 'Mediawiki')], max_length=255)),
                ('server_type', models.CharField(choices=[(1, 'Standart'), (2, 'Basic'), (3, 'Premium')], max_length=255)),
                ('public_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('cpanel_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
