# Generated by Django 3.2.12 on 2022-03-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220318_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='user_admin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuario'),
            preserve_default=False,
        ),
    ]
