# Generated by Django 3.2.12 on 2022-03-18 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_servidor_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='user_admin',
            field=models.ForeignKey(default='anybody', on_delete=django.db.models.deletion.CASCADE, to='dashboard.usuario'),
        ),
    ]
