# Generated by Django 4.0.3 on 2022-06-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_servidor_user_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servidor',
            old_name='user_admin',
            new_name='user_admin_id',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='cpanel_password',
        ),
        migrations.AlterField(
            model_name='servidor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
