# Generated by Django 4.0.3 on 2022-06-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_user_admin_servidor_user_admin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
