# Generated by Django 4.0.3 on 2022-06-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_servidor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='cms_type',
            field=models.CharField(choices=[('Wordpress', 'Wordpress'), ('Prestashop', 'Prestashop'), ('Mediawiki', 'Mediawiki')], max_length=255),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='server_type',
            field=models.CharField(choices=[('Standart', 'Standart'), ('Basic', 'Basic'), ('Premium', 'Premium')], max_length=255),
        ),
    ]
